version: '3'

tasks:
  strict-install:
    cmds:
      - pnpm install --frozen-lockfile

  build:
    deps: [strict-install]
    cmds:
      - pnpm --filter @app/* build
      - pnpm --filter @services/* build