FROM node:16-alpine

ARG APP_DIR=/app

WORKDIR ${APP_DIR}

RUN ["mkdir", "/install"]

ADD ["./package.json", "/install"]
WORKDIR /install
RUN npm install --verbose
ENV NODE_PATH=/install/node_modules

WORKDIR /app